### ISSUE TITLE
Method for developing patch

### ISSUE THREAD

**Issue by re11ding** [Failzuma/JustAsPlanned#4]
Hey sorry! This isn't an issue per say. I only just found out about the game's existence like a few days ago and you're probably already aware, the DLC for owning everything from now and forever is gone. Therefore, I need to rely on things like this. 

I wanted to know the specifics on how you figure out what elements to change in the dll file. I understand how it works, but I don't understand how you know those are the aspects to change. There's always the chance that there will be an update that adds more things that need to be patched (I'm assuming anyway?) and, in case you don't wish to keep updating this, it would be nice to have the knowledge on how to find the parts to patch myself just in case I need to carry the torch. 

At the same time, I don't know if what I'm asking is allowed to be explained without the risk of it being patched and prevented. Please let me know if you would be willing to explain. If not, I totally understand. If it needs to be explained privately but you are willing to explain, let me know and we'll find a way to discuss privately. 

Sorry for asking of this! Again, I just want to make sure I can always access future content. In case you lose interest, I still want to be able to make it work myself by knowing how to update it. Even if you say no, I appreciate you at least considering it.

**Comment by Failzuma** [comment]
Hi!
Okay so let me make it quick. The specifics thing i changed in the `.dll` file is simply the pattern that points to the function / method that we need to patch in order to make it work.
For more details, you can dump the game using il2cppdumper and look for the methods. Then use tools like cheat engine or something similar, look up for the method address then create the pattern (this is to make sure the tool wont break if the game is getting a new update)
As far as I made this tool there aren't any new things that needs to be patched. But we'll see about that maybe in the future
